---
- name: Configure Dynamic Message of the Day
  hosts: all
  become: true
  remote_user: ansible
  
  vars:
    motd_dir: /etc/motd
    dyn_motd_dir: /etc/update-motd.d
    var_run_motd_dynamic: /var/run/motd.dynamic
    autoupgrade: 20auto-upgrades

    files:
      - 00-header 
      - 10-sysinfo-debian
      - 10-uname
      - 20-updates
      - 90-footer
      - 92-unattended-upgrades

  tasks:
  - name: clean run
    file:
      path: "{{ var_run_motd_dynamic }}"
      state: absent

  - name: motd exist
    stat:
      path: /etc/motd
    register: motd_exist 

  - name: rename motd
    command: mv /etc/motd /etc/motd.orig
    when: motd_exist.stat.exists == true

  - name: instal packages
    apt:
      state: present
      pkg:
        - unattended-upgrades
        - lsb-release
        - figlet
        - bc

  - name: auto-upgrades
    copy:
      src: files/20auto-upgrades
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      backup: true

  - name: services unattended-upgrades
    systemd: 
      name: unattended-upgrades.service
      state: started
      enabled: yes

  - name: destintaion directory
    file:
      path: "{{ dyn_motd_dir }}"
      state: directory
      mode: 0755

  - name: copy files
    copy:
      dest: "{{ dyn_motd_dir }}"
      src: "{{ item }}"
      mode: 0755
    with_items: "{{ files }}"
